Changes made for button
manniL/lichter.io pull request #125
Opened 2024-01-08 05:03 UTC by kisharnath

2024-01-08 08:26 UTC, manniL requested changes
Thanks for the initial changes! Could we:

1) Stick to TailwindCSS?
2)  Still use the AppButton for the buttons? 🤔

2024-01-09 05:28 UTC, kisharnath commented
I am unable to find the right class for this ,Should I make custom class in tailwind?
And (Still use the AppButton for the buttons? )  This means can AppButton be used as button am I right?

2024-01-09 08:39 UTC, manniL commented
@kisharnath The idea that this button should work with less elements. If tailwind doesn't have the utilities for it, you can use it's [arbitrary syntax](https://tailwindcss.com/docs/adding-custom-styles#using-arbitrary-values).
Default: ![image](https://github.com/manniL/lichter.io/assets/640208/5ae19bf6-8019-4c42-8ba6-6aed021327d9)
On Hover:
![image](https://github.com/manniL/lichter.io/assets/640208/51305e72-41e1-459d-89de-58509c64a7f9)

2024-01-09 13:23 UTC, kisharnath commented
Can you check now?

2024-01-09 15:42 UTC, manniL requested changes

2024-01-09 15:42 UTC, manniL commented on assets/css/tailwind.css
> +.newButton{
As mentioned, please use Tailwinds Arbitrary syntax ☺️ 
If that is not possible at all, Vue's scoped styles are also fine, but then use `@apply` where possible

2024-01-18 05:32 UTC, kisharnath commented
Can you check out now ?

2024-02-11 15:55 UTC, manniL commented
Hey @kisharnath! Thanks for your work so far. Unfortunately, the styles don't match the original. The border on the side is thinner than on the top and bottom. Also, when hovering there is no gradient anymore.
![image](https://github.com/manniL/lichter.io/assets/640208/fe62dbae-d5d5-46f6-8402-049a74d7c4ee)

2024-02-15 06:04 UTC, kisharnath commented
Please  check now

2024-02-15 08:14 UTC, manniL commented
@kisharnath can you check my comments @ https://youtu.be/K-2r2rXHEdo?t=6528? ☺️

2024-02-21 05:01 UTC, closed without merging